name: Sparx Instant Cloud
on: 
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL'
        required: true

jobs:
  turbo-burst:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: pip install aiohttp
      - name: Launch
        env:
          TARGET_URL: ${{ github.event.inputs.target }}
        run: python sparx.py
